name: Build-OpenCV

on:
  push:
    branches: [ feature/docker ]
    paths: [ .github/workflows/opencv.yml ]
  workflow_dispatch:

env:
  OPENCV_VERSION: 4.11.0
  OPENCV_CMAKE_ARGS: >-
    -D CMAKE_BUILD_TYPE=Release
    -D OPENCV_FORCE_3RDPARTY_BUILD=ON
    -D OPENCV_EXTRA_MODULES_PATH="${{ github.workspace }}/opencv_contrib/modules"
    -D CMAKE_INSTALL_PREFIX="${{ github.workspace }}/opencv/build/install"
    -D BUILD_LIST=core,imgproc,imgcodecs,videoio
    -D BUILD_SHARED_LIBS=OFF
    -D BUILD_EXAMPLES=OFF
    -D BUILD_DOCS=OFF
    -D BUILD_PERF_TESTS=OFF
    -D BUILD_TESTS=OFF
    -D BUILD_JAVA=OFF
    -D WITH_GSTREAMER=ON
    -D WITH_DSHOW=ON
    -D WITH_AVFOUNDATION=ON
    -D WITH_ADE=OFF
    -D WITH_FFMPEG=OFF
    -D WITH_V4L=OFF
    -D WITH_1394=OFF
    -D WITH_GTK=OFF
    -D WITH_OPENEXR=OFF
    -D WITH_PROTOBUF=OFF
    -D WITH_QUIRC=OFF
    -D WITH_EIGEN=OFF
    -D ENABLE_EIGEN=OFF
    -D EIGEN_INCLUDE_PATH=OFF
    -D OPENCV_ENABLE_NONFREE=OFF

jobs:
  build:
    defaults:
      run:
        shell: bash

    runs-on: ${{ matrix.runs-on }}

    strategy:
      matrix:
        include:
        - { os: ubuntu.22.04, arch: x64,   runs-on: ubuntu-22.04 }
        - { os: ubuntu.22.04, arch: arm64, runs-on: ubuntu-22.04-arm }
        - { os: win,          arch: x64,   runs-on: windows-2022 }
        - { os: win,          arch: x86,   runs-on: windows-2022 }
        - { os: win,          arch: arm64, runs-on: windows-11-arm }
        # - { os: osx,          arch: x64,   runs-on: macos-13 }
        # - { os: osx,          arch: arm64, runs-on: macos-14 }
        - { os: android,      arch: arm64, runs-on: ubuntu-22.04 }
        - { os: android,      arch: x64,   runs-on: ubuntu-22.04 }

    steps:
    - name: Checkout OpenCV repo
      uses: actions/checkout@v4
      with:
        repository: opencv/opencv
        ref: ${{ env.OPENCV_VERSION }}
        path: opencv
        fetch-depth: 1

    - name: Checkout OpenCV Contrib repo
      uses: actions/checkout@v4
      with:
        repository: opencv/opencv_contrib
        ref: ${{ env.OPENCV_VERSION }}
        path: opencv_contrib
        fetch-depth: 1

    - name: Install Dependencies
      run: |
        if [[ "${{ matrix.os }}" =~ ^ubuntu || "${{ matrix.os }}" == "android" ]]; then
          script=$(
            cat <<'EOS'
            set -eux
            sudo apt update
            sudo apt install -y libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev gstreamer1.0-plugins-good libunwind-dev
        EOS
          )
        elif [[ "${{ matrix.os }}" == "osx" ]]; then
          script=$(
            cat <<'EOS'
            set -eux
            brew update
        EOS
          )
        elif [[ "${{ matrix.os }}" == "win" ]]; then
          script=$(
            cat <<'EOS'
            set -eux
        EOS
        )
        fi
        
        bash -c "$script"

    - name: Configure OpenCV
      run: |
        script=$(
          cat <<'EOS'
          set -eux
          EXTRA_FLAGS=""
          if [[ "${{ matrix.os }}" == "win" && "${{ matrix.arch }}" == "arm64" ]]; then
            EXTRA_FLAGS+=" -DWITH_IPP=OFF -DCPU_BASELINE=NEON -A ARM64"
          elif [[ "${{ matrix.os }}" == "win" && "${{ matrix.arch }}" == "x86" ]]; then
            EXTRA_FLAGS+=" -A Win32"
          elif [[ ${{ matrix.os }} == "centos.7" ]]; then
            EXTRA_FLAGS+=" -DCMAKE_C_FLAGS='-std=gnu99'"
            ln -s /usr/bin/cmake3 /usr/bin/cmake
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              echo "::group::Disable NEON in libwebp for CentOS 7 ARM64"
              sed -i 's/\<WEBP_USE_NEON\>/WEBP_USE_NEON_DISABLED/' opencv/3rdparty/libwebp/src/dsp/yuv_neon.c
              cat opencv/3rdparty/libwebp/src/dsp/yuv_neon.c
              echo "::endgroup::"
            fi
          elif [[ "${{ matrix.os }}" == "android" ]]; then
            echo "Configuring for Android / ${{ matrix.arch }}"
          
            EXTRA_FLAGS+=" -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK/build/cmake/android.toolchain.cmake"
            EXTRA_FLAGS+=" -DANDROID_PLATFORM=android-24"
            EXTRA_FLAGS+=" -DANDROID_STL=c++_static"
            EXTRA_FLAGS+=" -DBUILD_ANDROID_EXAMPLES=OFF DBUILD_ANDROID_PROJECTS=OFF"
            EXTRA_FLAGS+=" -Wno-dev"
          
            if [[ "${{ matrix.arch }}" == "arm64" ]]; then
              EXTRA_FLAGS+=" -DANDROID_ABI=arm64-v8a"
            elif [[ "${{ matrix.arch }}" == "x64" ]]; then
              EXTRA_FLAGS+=" -DANDROID_ABI=x86_64"
            fi
          fi

          cd opencv && mkdir build && cd build
          cmake ${{ env.OPENCV_CMAKE_ARGS }} $EXTRA_FLAGS ..
        EOS
        )

        if [[ "${{ matrix.image }}" == "" ]]; then
          bash -c "$script"
        else
          docker exec builder /bin/sh -c "$script"
        fi

    - name: Build OpenCV
      run: |
        script=$(
          cat <<'EOS'
          set -eux
          cd opencv/build
          if [[ "${{ matrix.os }}" =~ ^win ]]; then
            cmake --build . --config Release
          else
            make -j$(nproc)
          fi
        EOS
        )

        bash -c "$script"

    - name: Install OpenCV
      run: |
        script=$(
          cat <<'EOS'
          cd opencv/build
          if [[ "${{ matrix.os }}" =~ ^win ]]; then
             cmake --install . --config Release
          else
            make install
          fi
        EOS
        )

        bash -c "$script"

    - name: Show Build Artifacts
      run: |
        cd opencv/build && ls -lR

    - name: Make artifacts
      run: |
        mkdir artifacts
        cp -r opencv/build/install/* artifacts

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: opencv-${{ matrix.os }}-${{ matrix.arch }}
        path: artifacts
